ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM anon;
GRANT EXECUTE ON FUNCTION public.recalculate_xp() TO authenticated;
GRANT EXECUTE ON FUNCTION public.recalc_xp() TO authenticated;
GRANT EXECUTE ON FUNCTION public.award_xp(integer, text, public.skill_category) TO authenticated;
GRANT EXECUTE ON FUNCTION public.award_xp(integer, text, public.skill_category, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_habit_today(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_focus_session(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bad_habit_relapse(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bad_habit_sync_awards() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_weekly_boss_progress() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_weekly_boss(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.project_future(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_activity_heatmap(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_life_state() TO authenticated;
GRANT EXECUTE ON FUNCTION public.equip_title(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_all_titles(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_rank(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calc_life_score(uuid) TO authenticated;